// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ykoltgugcwcdahcknmqs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlrb2x0Z3VnY3djZGFoY2tubXFzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2OTE1MDQsImV4cCI6MjA1OTI2NzUwNH0.qXISc3biIbL51YQpoNhyc_xRPqltuA5SPfasrTRb4rI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);